name: Build and publish binaries (releases only)
on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: ["386", amd64]
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: build binaries
      uses: wangyoucao577/go-release-action@v1.20
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        ldflags: '-linkmode external -extldflags "-static" -s -w'
        pre_command: bash ./install-deps.sh
        binary_name: "openvpn-user"
        asset_name: openvpn-user-${{ matrix.goos }}-${{ matrix.goarch }}.
